---
title: "Python to R: Dataframes Basics"
author: Nischal Shrestha
output: 
  learnr::tutorial:
    fig_caption: no
    progressive: no
    allow_skip: true
    toc: true
    toc_depth: 2
    toc_float: true
    css: "./css/custom_css.css"
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
# first, some packages for interactive tutorial, polyglot environment and tidyverse
library(learnr)
library(gradethis)
library(reticulate)
library(tidyverse)
library(glue)
library(rlang)
library(knitr)
library(rmarkdown)
# # code checking options
shiny_prerendered_clean('learnr_reticulate_transfer.Rmmd')
tutorial_options(exercise.timelimit = 60, exercise.completion = FALSE, exercise.checker = gradethis::grade_learnr)
# # by default, let's not show code as many are written for learnr
opts_chunk$set(echo = FALSE)
opts_chunk$set(comment = NA)
```

<!-- Some data dependencies -->
```{python include = FALSE, context="data"}
# set a python variable to point to mtcars
mtcars = r.mtcars
```

```{r bracket-df, eval=TRUE, include=FALSE, context="data"}
df <- data.frame(a=c(1,2,NA), b=c(NA, 4, 5), c=c(6,7,8))
```

```{python include=FALSE, context="data"}
df = r.df
```


<!-- Include all topic Rmds. Order is important! -->
```{r}
child_docs <- c("introduction.Rmd",
                "inspection.Rmd",
                "indexing.Rmd",
                "filteringdata.Rmd",
                "entertidy.Rmd",
                "slice.Rmd",
                "select.Rmd",
                "filter.Rmd")
child_docs <- map_chr(child_docs, function(x) glue("./topics/", x))
```

```{r child = child_docs}

```