---
title: "Introduction"
output: html_document
---

## Introduction

### What is this?

This is a short guide for Python programmers on handling dataframes in R. This document is interactive which means you will get to execute code as you follow along each topic. It also presents R from the perspective of a Python programmer and possible gotchas you need to watch out for as you begin your R journey.

### What am I going to learn?

This guide is made up of 11 topics around dataframe manipulation. We begin with the basics of R dataframes with base R---what you get from the R without additional packages. Then, we spend a large portion covering a new style of programming called tidy R, introduced by the [tidyverse](https://www.tidyverse.org) packages. Tidy R is a style that provides some usability improvements to base R.

### How am I going to learn?

You are going to read some text to learn facts about R and its widely used operations and functions, but most importantly, you are going to make use of a lot of "learning by doing". Learning happens best when applying what you have learned, so each topic will contain mini code exercises where you can write and execute R code! This can help reinforce the concepts covered in each topic.

You can choose to go in order or skip around topics. All exercises can be skipped as well. Throughout the topics, we shall use the **mtcars** dataset available in R.
